### PR TITLE
Upgrade Angular 9

### PR DESCRIPTION
**Pull request by preeco-privacy**
Upgrade for Angular 9

In `CanvasWhiteboardComponent` in `@ViewChild()` I added `{static: true}` to make the elements available in `ngOnInit()`.

I updated some dependencies, too.

The other changes are only in the compiled and bundled outputs.

### CODE REVIEW

**Comment by LukeSkelhorn** [comment]
When is this going to get merged in?

**Comment by preeco-privacy** [comment]
The last commit removes a warning during install 

```
WARNING in Entry point 'ng2-canvas-whiteboard' contains deep imports into 'node_modules/rxjs/index'. 
This is probably not a problem, but may cause the compilation of entry points to be out of order. 
```

I fixed this warning by changing wrong imports from `rxjs/index` into `rxjs`.

**Comment by krsandhu** [comment]
Any plan to release this update?

**Comment by Peshou** [comment]
Hi, sorry for the delay.

Everything looks good, but there is one more component which needs the `static: true` to its view child, the canvas-whiteboard-colorpicker.component.

Will add this now, merge the branches and make a new minor version upgrade.

Cheers, thanks a lot.

**Pull request merged**
